CREATE SEQUENCE BOOK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CUSTOMER_SEQ START WITH 1 INCREMENT BY 1;

--CREATE SEQUENCE category_seq START WITH 1 INCREMENT BY 1;
